import { Item, Notification } from "./types";

export const dummyItems: Item[] = [
  {
    id: "1",
    title: "Blue Backpack",
    description: "Navy blue JanSport backpack with a laptop compartment. Has a small scratch on the front pocket. Contains notebooks and a pencil case.",
    location: "Library",
    status: "lost",
    type: "lost",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop",
    postedBy: "Rahul Sharma",
    postedAt: "2026-04-01T10:30:00Z",
    contactEmail: "rahul@srit.ac.in",
  },
  {
    id: "2",
    title: "iPhone 15 Pro",
    description: "Space black iPhone 15 Pro with a clear case. Lock screen has a mountain wallpaper.",
    location: "Canteen",
    status: "found",
    type: "found",
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=300&fit=crop",
    postedBy: "Priya Patel",
    postedAt: "2026-04-01T14:15:00Z",
    contactEmail: "priya@srit.ac.in",
  },
  {
    id: "3",
    title: "Student ID Card",
    description: "College ID card found near the parking lot. Name partially visible.",
    location: "Parking Lot",
    status: "found",
    type: "found",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop",
    postedBy: "Amit Kumar",
    postedAt: "2026-03-31T09:00:00Z",
    contactEmail: "amit@srit.ac.in",
  },
  {
    id: "4",
    title: "Silver Watch",
    description: "Fossil silver analog watch with a metal band. Lost during sports practice.",
    location: "Sports Complex",
    status: "lost",
    type: "lost",
    imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=300&fit=crop",
    postedBy: "Sneha Reddy",
    postedAt: "2026-03-31T16:45:00Z",
    contactEmail: "sneha@srit.ac.in",
  },
  {
    id: "5",
    title: "Wireless Earbuds",
    description: "White Samsung Galaxy Buds2 Pro in charging case. Found on a bench.",
    location: "Block A",
    status: "claimed",
    type: "found",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400&h=300&fit=crop",
    postedBy: "Vikram Singh",
    postedAt: "2026-03-30T11:20:00Z",
    contactEmail: "vikram@srit.ac.in",
  },
  {
    id: "6",
    title: "Calculus Textbook",
    description: "Thomas' Calculus 14th Edition. Has highlighted pages and sticky notes throughout.",
    location: "Computer Lab",
    status: "lost",
    type: "lost",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=300&fit=crop",
    postedBy: "Ananya Gupta",
    postedAt: "2026-03-30T08:10:00Z",
    contactEmail: "ananya@srit.ac.in",
  },
  {
    id: "7",
    title: "Water Bottle",
    description: "Green Hydro Flask 32oz water bottle with stickers on it. Left behind after class.",
    location: "Block B",
    status: "found",
    type: "found",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=300&fit=crop",
    postedBy: "Karan Mehta",
    postedAt: "2026-03-29T13:30:00Z",
    contactEmail: "karan@srit.ac.in",
  },
  {
    id: "8",
    title: "Prescription Glasses",
    description: "Black rectangular frame glasses in a brown leather case. Found in auditorium seat.",
    location: "Auditorium",
    status: "found",
    type: "found",
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f7977603b6d2?w=400&h=300&fit=crop",
    postedBy: "Divya Nair",
    postedAt: "2026-03-29T17:00:00Z",
    contactEmail: "divya@srit.ac.in",
  },
];

export const dummyNotifications: Notification[] = [
  { id: "1", message: "A potential match was found for your lost Blue Backpack!", read: false, createdAt: "2026-04-01T15:00:00Z", itemId: "1" },
  { id: "2", message: "Someone submitted a claim for your found iPhone 15 Pro.", read: false, createdAt: "2026-04-01T14:30:00Z", itemId: "2" },
  { id: "3", message: "Your claim for Wireless Earbuds has been approved.", read: true, createdAt: "2026-03-30T12:00:00Z", itemId: "5" },
  { id: "4", message: "New found item posted near Library — might match your lost item.", read: true, createdAt: "2026-03-30T10:00:00Z" },
];

export const currentUser = {
  name: "Rahul Sharma",
  email: "rahul@srit.ac.in",
};
